JWTUtils:
  wx:
    signature: "wxSignature"
    minute: 300
  manager:
    signature: "managerSignature"
    minute: 300

WXApi:
  appid: "wx7ba9c5031955766f"
  secret: "283c6c34a2344d044e4b8229cc1bda2d"

Picture:
  pattern: "/img/**"
  path: "/data/img/"
