
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/smallprogram?useSSL=true&serverTimezone=UTC&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 80
